// ==================== UPGRADES ====================
const UPGRADES=[
{ id:'dmgUp',cat:'off',weight:8,charReq:null,apply:(g,n)=>{g.atk*=1+0.12*n}},
{ id:'atkSpdUp',cat:'off',weight:8,charReq:null,apply:(g,n)=>{g.atkSpd*=1+0.12*n}},
{ id:'critChanceUp',cat:'off',weight:6,charReq:null,apply:(g,n)=>{g.crit+=0.06*n}},
{ id:'critDmgUp',cat:'off',weight:6,charReq:null,apply:(g,n)=>{g.critDmg+=0.20*n}},
{ id:'projCount',cat:'off',weight:3,charReq:'gunslinger',apply:(g,n)=>{g.projCount+=n}},
{ id:'pierceShot',cat:'off',weight:3,charReq:'gunslinger',apply:(g,n)=>{g.piercing+=n}},
{ id:'cleaveArcUp',cat:'off',weight:3,charReq:'guardian',apply:(g,n)=>{g.cleaveArc+=Math.PI/7.2*n}},
{ id:'cleaveRangeUp',cat:'off',weight:3,charReq:'guardian',apply:(g,n)=>{g.autoRange*=1+0.15*n}},
{ id:'shadowRangeUp',cat:'off',weight:3,charReq:'shadow',apply:(g,n)=>{g.autoRange*=1+0.20*n}},
{ id:'afterDmgUp',cat:'off',weight:3,charReq:'shadow',apply:(g,n)=>{g.afterimageMult*=(1+0.20*n)}},
{ id:'chainLightning',cat:'off',weight:4,charReq:null,apply:(g,n)=>{const stacks=g.upgradeStacks['chainLightning']||0;g.chainChance=0.25+0.1*stacks;g.chainDmg=0.4}},
{ id:'burningStrikes',cat:'off',weight:4,charReq:null,apply:(g,n)=>{const stacks=g.upgradeStacks['burningStrikes']||0;g.burnDmg=2+stacks;g.burnDur=3}},
{ id:'maxHPUp',cat:'def',weight:8,charReq:null,apply:(g,n)=>{g.maxHP+=15*n;g.hp=Math.min(g.hp+15*n,g.maxHP)}},
{ id:'armorUp',cat:'def',weight:6,charReq:null,apply:(g,n)=>{g.armor+=2*n}},
{ id:'hpRegen',cat:'def',weight:6,charReq:null,apply:(g,n)=>{g.hpRegen+=0.8*n}},
{ id:'shield',cat:'def',weight:4,charReq:null,apply:(g,n)=>{g.hasShield=true;const stacks=g.upgradeStacks['shield']||0;g.shieldCD=Math.max(8,18-2*stacks)}},
{ id:'dodgeChance',cat:'def',weight:4,charReq:null,apply:(g,n)=>{g.dodgeChance+=0.06*n}},
{ id:'thorns',cat:'def',weight:3,charReq:null,apply:(g,n)=>{g.thorns+=0.12*n}},
{ id:'lifeSteal',cat:'def',weight:3,charReq:null,apply:(g,n)=>{g.lifeSteal+=0.04*n}},
{ id:'moveSpdUp',cat:'util',weight:7,charReq:null,apply:(g,n)=>{g.spd*=1+0.10*n}},
{ id:'pickRangeUp',cat:'util',weight:5,charReq:null,apply:(g,n)=>{g.pickupRange*=1+0.25*n}},
{ id:'goldBonus',cat:'util',weight:5,charReq:null,apply:(g,n)=>{g.goldMult*=(1+0.15*n)}},
{ id:'xpBonus',cat:'util',weight:5,charReq:null,apply:(g,n)=>{g.xpMult*=(1+0.15*n)}},
{ id:'cdr',cat:'util',weight:4,charReq:null,apply:(g,n)=>{g.ultCDMult*=(1-0.12*n)}},
{ id:'magnetField',cat:'util',weight:3,charReq:null,apply:(g,n)=>{g.magnetField=(g.magnetField||0)+0.15*n}},
{ id:'fortune',cat:'util',weight:3,charReq:null,apply:(g,n)=>{g.fortune+=0.10*n}},
{ id:'orbitalShield',cat:'spec',weight:4,charReq:null,apply:(g,n)=>{const stacks=g.upgradeStacks['orbitalShield']||0;g.orbitalShield=2+stacks}},
{ id:'lightningAura',cat:'spec',weight:4,charReq:null,apply:(g,n)=>{g.lightningAuraDmg=(g.lightningAuraDmg||0)+8*n;g.lightningAuraCD=(g.lightningAuraCD||2.5)}},
{ id:'frozenTrail',cat:'spec',weight:3,charReq:null,apply:(g,n)=>{g.frozenTrail=true;const stacks=g.upgradeStacks['frozenTrail']||0;g.frozenTrailSlow=0.3+0.1*stacks}},
{ id:'whirlwind',cat:'spec',weight:3,charReq:null,apply:(g,n)=>{g.whirlwind=true;const stacks=g.upgradeStacks['whirlwind']||0;g.whirlwindRange=50+8*stacks;g.whirlwindCD=6}},
{ id:'fortressExt',cat:'char',weight:3,charReq:'guardian',apply:(g,n)=>{g.ultShockwaveRange=(g.ultShockwaveRange||120)+20*n;g.ultDuration=(g.ultDuration||3)+0.5*n}},
{ id:'bulletStorm',cat:'char',weight:3,charReq:'gunslinger',apply:(g,n)=>{g.ultBullets=(g.ultBullets||3)+n}},
{ id:'shadowDance',cat:'char',weight:3,charReq:'shadow',apply:(g,n)=>{g.ultClones=(g.ultClones||1)+n;g.ultDuration=(g.ultDuration||5)+0.5*n}}
];
const CAT_W={off:0.30,def:0.25,util:0.20,spec:0.15,char:0.10};